name: Build Application
run-name: ${{ github.actor }} is creating PR

on:
  pull_request:
    branches:
      - dev
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Setup Env
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 20
      #     cache: "yarn"
      #     cache-dependency-path: "**/yarn.lock"

      # - name: Cache Packages
      #   uses: actions/cache@v3
      #   id: package-cache
      #   with:
      #     path: "**/node_modules"
      #     key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-yarn-

      # - name: Install Package
      #   if: steps.package-cache.outputs.cache-hit != 'true'
      #   run: yarn

      # - name: Build Application
      #   run: yarn build

  notify:
    name: Notify PR Created
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Get Code
        uses: actions/checkout@v4

      - name: Post Google Chat Message
        uses: ./.github/actions/pr-notifer
        with:
          prNumber: ${{ github.event.pull_request.number }}
          creator: ${{ github.event.pull_request.user.login }}
          repo_name: ${{ github.event.repository.name }}
          source_branch: ${{ github.event.pull_request.head.ref || github.ref }}
          target_branch: ${{ github.event.pull_request.base.ref }}
          pr_title: ${{ github.event.pull_request.title }}
          label: "- ${{ join( github.event.pull_request.labels.*.name, ', ') }}"
          reviewer: "- ${{ join(github.event.pull_request.requested_reviewers.*.login) }}"
          assigner: "- ${{ join(github.event.pull_request.assignees.*.login) }}"
          pr_html_url: ${{ github.event.pull_request.html_url }}
